### ISSUE TITLE
Ingredients list

### ISSUE THREAD

**Issue by JansthcirlU** [JansthcirlU/RecipesRxJS#11]
Create a component that shows the ingredients used in a recipe.

#### Tasks

- [ ] Create `ingredient-list` component
- [ ] Put the component inside the recipe details component

#### Acceptance criteria

- [ ] I should be able to see a list of ingredients used in a recipe
- [ ] I should be able to see the quantities of each ingredient used
