### ISSUE TITLE
Preparation steps

### ISSUE THREAD

**Issue by JansthcirlU** [JansthcirlU/RecipesRxJS#12]
Create a list of preparation steps so that people can follow along how to create the meal.

#### Tasks

- [ ] Create `preparation-steps` component containing the basic steps
- [ ] Create `preparation-step-card` component with more detailed step info

#### Acceptance criteria

- [ ] I should be able to see an ordered and numbered list of preparation steps
- [ ] I should see a summary that describes each step
- [ ] I should be able to click a step to see its details in a dialog
