### ISSUE TITLE
Time details

### ISSUE THREAD

**Issue by JansthcirlU** [JansthcirlU/RecipesRxJS#13]
Create an overview for how long it will approximately take to prepare and cook the meal.

#### Tasks

- [ ] Show the time to prepare for the meal (i.e. arrangement of ingredients, waiting for things to happen, etc.)
- [ ] Show the time to cook the meal

#### Acceptance criteria

- [ ] I should be able to see the approximate time it takes to prepare the meal
- [ ] I should be able to see the approximate time it takes to cook the meal
