### ISSUE TITLE
Preparation walkthrough

### ISSUE THREAD

**Issue by JansthcirlU** [JansthcirlU/RecipesRxJS#17]
Create a list of checkable, more detailed preparation steps, akin to a to-do list with progress.

#### Tasks

- [ ] Create `preparation-checklist-step` component to track step progress (and sub-tasks, etc.)
- [ ] Create `preparation-checklist` component to track executed steps

#### Acceptance criteria

- [ ] I should be able to start working on any step
- [ ] I should be able to mark any step as done
- [ ] I should be able to distinguish active steps from those which are done or have not started yet
- [ ] I should be able to see automatic progress for steps with a known duration (e.g. cook for 15 minutes)
- [ ] I should be able to see the total progress of the checklist
