### ISSUE TITLE
General info

### ISSUE THREAD

**Issue by JansthcirlU** [JansthcirlU/RecipesRxJS#20]
Create a form page to enter general information about the recipe to be created.

#### Tasks

- [ ] Title
- [ ] Description
- [ ] One or more pictures
- [ ] Difficulty level
- [ ] Tags

#### Acceptance criteria

- [ ] I must provide a title for the recipe (max. 60 characters)
- [ ] I must provide a description for the recipe (max. 25 words)
- [ ] I must provide at least one image of the finished meal
- [ ] I must provide a difficulty level
- [ ] I must provide tags
