### ISSUE TITLE
Page layout with navbar

### ISSUE THREAD

**Issue by JansthcirlU** [JansthcirlU/RecipesRxJS#7]
Create page layout with a navbar and a main section. Name the elements appropriately for testability.

#### Tasks
- [x] Remove placeholder content from [`app.component.html`](https://github.com/JansthcirlU/RecipesRxJS/blob/3989d26b99f1feae401fe00a24f2a58c86c8e80c/recipes-rxjs/src/app/app.component.html)
- [x] Add a [`header`](https://www.w3schools.com/tags/tag_header.asp) containing a [`nav`](https://www.w3schools.com/tags/tag_nav.asp) in the top right corner for future navigation links and a logo placeholder in the top left corner
- [x] Add a [`main`](https://www.w3schools.com/tags/tag_main.asp) to contain the content

#### Acceptance criteria
- [x] I should be able to see a header that is separate from the main content with placeholder content

**Comment by Brdekrom** [comment]
I want access to the checkboxes

**Comment by Brdekrom** [comment]
This issue is fully done
