### ISSUE TITLE
Recipe overview component

### ISSUE THREAD

**Issue by JansthcirlU** [JansthcirlU/RecipesRxJS#9]
Create a responsive grid that contains an overview of cards that show basic recipe info: title, rating and picture.

#### Tasks

- [ ] Create `recipe-card` component to show a single recipe entry
- [ ] Create responsive `recipes-overview` component (e.g. [flexbox](https://www.w3schools.com/css/css3_flexbox.asp) or [grid](https://www.w3schools.com/css/css_grid.asp))
- [ ] Put the overview component inside the `main` section of `app.component.html`

#### Acceptance criteria

- [ ] I should be able to see existing recipes
- [ ] I should see the title of each displayed recipe
- [ ] I should see the rating of each displayed recipe
- [ ] I should see the image (or placeholder) of each displayed recipe
- [ ] I should see the number of recipes the overview contains in real time

**Comment by Brdekrom** [comment]
Na merge zal ik hieraan werken

**Comment by Brdekrom** [comment]
Deze mag afgesloten worden :)
